"""add password column

Revision ID: c00fe712d306
Revises: 
Create Date: 2026-03-26 14:00:29.666720

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00fe712d306'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'Email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Email', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
